name: Build docker images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The docker image tag'
        required: true
  push:
    branches:
      - master

env:
  GIT_LFS_SKIP_SMUDGE: 1

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        make:
          - name: Build Specs docs image
            image: specs
            path: specs
            secret_name_suffix: _SPECS
          - name: Build Docs docs image
            image: docs
            path: docs
            secret_name_suffix: _DOCS
          - name: Build Dev docs image
            image: dev
            path: dev
            secret_name_suffix: _DEV

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to private registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: ${{ matrix.make.name }}
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: '${{ secrets.REGISTRY_URL }}/namada/${{ matrix.make.image }}-docs:latest'
          cache-from: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/namada/${{ matrix.make.image }}-docs:buildcache'
          cache-to: 'type=registry,ref=${{ secrets.REGISTRY_URL }}/namada/${{ matrix.make.image }}-docs:buildcache,mode=max'
          build-args:
            path=${{ matrix.make.path }}
      - name: Set secret name
        id: vars
        if: github.ref == 'refs/heads/master'
        # run: curl -I -X POST ${{ secrets[matrix.make.secret_name] }} --fail
        run: echo "::set-output name=UPDATE_URL::${SECRET_NAME}"
        env:
          SECRET_NAME: ${{ format('UPDATE_URL{0}', matrix.make.secret_name_suffix) }}
      - name: Update image
        if: github.ref == 'refs/heads/master'
        run: echo ${{ steps.vars.outputs.UPDATE_URL }} && curl -I -X POST https://portainer.heliax.click/api/webhooks/232b09f2-9332-40a5-a290-68591a7d4eb5 --fail
      