name: Build docker images

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The docker image tag'
        required: true
  push:
    branches:
      - master

env:
  GIT_LFS_SKIP_SMUDGE: 1

jobs:
  docker:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]
        make:
          - name: Build Specs docs image
            image: specs
            path: specs
            secret_name_suffix: _SPECS
          - name: Build Docs docs image
            image: docs
            path: docs
            secret_name_suffix: _DOCS
          - name: Build Dev docs image
            image: dev
            path: dev
            secret_name_suffix: _DEV

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@1.0.2
      - name: Login to private registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.REGISTRY_URL }}/namada-${{ matrix.make.image }}-docs
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest
      - name: ${{ matrix.make.name }}
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            path=${{ matrix.make.path }}
      